### PR TITLE
added stanza for comparison (POS-tagging)

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
Similarly, UDpipe seems to also be lacking here

**Comment by AmaliePauli** [comment]
Hi @KennethEnevoldsen ,
Thanks for pointing towards the stanza models.
However, for consistency, we want to benchmark the models in the same script as the rest of the performance we report in https://github.com/alexandrainst/danlp/tree/master/examples/benchmarks
So the stanza models should be added to the banchmark sctipt first. I can open an issue with it, on less you want to add it to this pull request?

**Comment by KennethEnevoldsen** [comment]
Hmm will not have the times as it stands, but feel free to create an issue. I might get to it when I have the chance

**Comment by AmaliePauli** [comment]
Link to new issue #93

**Pull request closed without merging**
