### PR TITLE
adding dacy to danlp

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**
I have added the DaCy model, including checks and performance on the test set of DaNE. I have restrained from editing the code in such a way that it would break compatibility, however as this model requires Spacy v.3.

if you want to provide a direct download link via. DaNLP the model can be downloaded [here](https://filesender.deic.dk/?s=download&token=b993e12c-0a75-880a-86d5-53d2c70b201c) (this is not a permanent link) or from the github:

https://github.com/KennethEnevoldsen/DaCy

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
I have added a "(✅)" to the column on whether it will be on DaNLP. That is naturally assuming you want to host it. If that is not something you want, we can naturally change it, and then I will figure out a way to make a permanent download link from our end.

best

**Comment by ophelielacroix** [comment]
Hi Kenneth,

we won't upgrade the package yet with spaCy >v3 (but we should do it in the future so let's keep the integration of your models for future improvement).  

In accordance with this, I propose for now to remove
- the modifications made under the danlp folder and in the requirements
- the test script

It seems that the benchmark scripts are not compatible with the new version of spaCy. 
There are several problems : 
- tokens_from_list is deprecated, instead you should do (in order to evaluate on the DDT tokenization) 
`from spacy.tokens import Doc
doc = Doc(nlp.vocab, words=["Hej", "!"])
`
- the path to the model is not correct, what about using your dacy package? such as
`
import dacy
nlp = dacy.load(model_name)
` 
- `parser = nlp` would not work because nlp cannot be applied to a Doc, instead use first 
`transformer = nlp.get_pipe('transformer')
  parser = nlp.get_pipe('parser')`
so that you can apply both on a Doc:
` doc = transformer(doc)
   doc = parser(doc)
`
- tok.pos_ should be replaced with tok.tag_

I also propose to add model_name as an argument of the dacy benchmark functions so that you can call it on each model in the main function. But for now, I would keep these calls as comments in the main functions as it requires an upgrade of spaCy and would not be compatible with the other functions. 

Once the benchmark scripts work, please update the score with what you obtain by running them.

**Comment by KennethEnevoldsen** [comment]
Thanks, Ophelia, 

I will take a look at this once a window of time opens up. The performance scores however should remain unchanged unless the default split is not constant. Will naturally change them if they are not the same, but that would mean a difference in DaNLP and SpaCy measures of performance. Which I would be surprised to see.

**Comment by KennethEnevoldsen** [comment]
Thanks for the correction, Ophelia. I have updated it accordingly. 

The performance changes are primarily because the 'correct' tokenization is given to DaCy, which results in a better performance overall. However, this is probably slightly misleading as tokenization is naturally not given to the model in any real scenario.

**Comment by ophelielacroix** [comment]
> Thanks for the correction, Ophelia. I have updated it accordingly.
> 
> The performance changes are primarily because the 'correct' tokenization is given to DaCy, which results in a better performance overall. However, this is probably slightly misleading as tokenization is naturally not given to the model in any real scenario.

Thanks for integrating the changes. It looks really good. 

For comparison between different systems, it is quite standard to apply it on gold tokenization in order to have scores that are actually comparable, i.e. systems are compared on the same bases. I agree that the scores do not represent performance in a "real scenario" but this way we compare the performance of the systems for one specific task only, independently from previous steps. 

One last question. I do not seem to be able to download the small model. Is it actually available or am I missing something?

**Comment by KennethEnevoldsen** [comment]
I agree with the use of the gold standard tokenization. Simply wanted to state it so that the cause for the change was apparent.

It should be available on the following link:
https://sciencedata.dk//shared/d845d4fef9ea165ee7bd6dd954b95de2?download
(taken directly from spacy).

Are you using the latest version from Github? If not I would love to see the error message - then I will look into the issue.

**Comment by ophelielacroix** [comment]
After downloading (using `nlp = dacy.load("da_dacy_small_tft-0.0.0")`), the model is called "da_dacy_-l-ctra_small_tft-0.0.0" instead of "da_dacy_small_tft-0.0.0" in my cache dir.
If I change the name for the last one it works. However the scores do not correspond to what you reported for the NER model: I get LOC/79.23 ORG/61.82 PER/88.52 while you have LOC/83.09 ORG/67.35 PER/89.62.

**Comment by KennethEnevoldsen** [comment]
Ahh, I see. I have fixed the naming issue. I also see I added the DaCy small to the NER. This wasn't my intention I have removed it.

I haven't tested the performance of the small DaCy model using the gold tokens. I initially planned to add it but choose to remove it as it compares unfavorably without a runtime efficiency. Do feel free to add it though. There is also a good chance I will update the model in the future. So as it seemed less permanent I would not bother adding it. (for this reason, I also just added versions numbers) 

The performance metrics from DaCy itself reflect the performance metrics reported by SpaCy (which does not use the golden standard tokens). 
https://github.com/KennethEnevoldsen/DaCy/tree/main/DaCy_training/metrics
(I have also added a note on this in DaCy)

(the numbers reported here for the small model is not correct. They are neither match the DaCy performance metrics nor the DaNLP. It is likely an error left there from some copy-paste action as the LOC matches the DaCy medium)

**Comment by ophelielacroix** [comment]
Ok, good.
So yes it makes sense to keep only the medium and large scores for now.

**Pull request merged**
